In [6]:
import numpy as np
 # initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [17]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d,array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [18]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d,array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n");

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [21]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
 # Stacking examples
hstacked = np.hstack((arr1, arr2))
 # Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked,"\n", vstacked,"\n",colstacked)

[[1 2 5 6]
 [3 4 7 8]] 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 
 [[1 5]
 [2 6]]


In [12]:
import numpy as np
arr1d=np.array([0,1,2,3,4,5,6])
arr2d=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr3d=np.array([[[0,1,2],[3,4,5],[6,7,8]],[[9,10,11],[12,13,15],[6,7,8]]])
print(arr2d)
print()
print(arr3d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 15]
  [ 6  7  8]]]


In [17]:
#slicing arrays to get sub arrays
# arr1d[1:4]
# arr2d[1:3,0:2]
# arr2d[0:2,1:3]
arr3d[0:2,0:3,1:3]  

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 15],
        [ 7,  8]]])

In [18]:
#Vectorization helps to replac explict Python loops to perfrom operations on entire arraay at once 

In [ ]:
#NumPy's internal impementaiton which is written in c 
#to execure computations much faster than looping overn elements in python
#Numpy provides vectorized functions for performing element wise 
#operations inplicitly unfunc(Universal funtion)--arithmetic operations

