# Array Creation

In [13]:
import numpy as np

#1
arr=np.empty([2,2])
print(arr)
arr1=np.ones([4,2])
arr1
n=int(input("Enter the number to fill array"))
filledArray=np.full((3,3),n)
print(filledArray)
newArray=np.zeros_like(filledArray)
print(newArray)

newOnesArray=np.ones_like(newArray)
print(newOnesArray)

new_list=[1,2,3,4,5]
arr_list=np.array(new_list)
print(arr_list)
print(type(arr_list))


[[1.33360329e+241 3.66256474e-311]
 [2.18045374e+241 7.73806985e-310]]
Enter the number to fill array5
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3 4 5]
<class 'numpy.ndarray'>


# Problem 2

In [25]:
#array with values raning from 10 to 49
new_arr=np.arange(10,49)
print(new_arr)
oneDArray=np.arange(9)
print(oneDArray)

#now to reshape above array to get 3 rows and 3 columns at it contains 9 elements
#we can now use np.reshape()
reshaped=np.reshape(oneDArray,(3,3))
print(reshaped)

Imatrix=np.eye(3)
print(Imatrix)




[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
randomArray=np.random.random(30)
print(randomArray)

mean=randomArray.mean()
print("The mean of the random array is ",mean)

print("\n Random 10 * 10 matrix ")
randomMatrix=np.random.random((10,10))
print(randomMatrix)

max_value=np.max(randomMatrix)
min_value=np.min(randomMatrix)

print(f"The maximum value for the array is{max_value} and minimum is {min_value} ")


[2.99984626e-01 9.06548369e-01 9.36947315e-01 6.09629084e-01
 1.50883688e-01 8.41573329e-04 7.65383643e-01 2.36042629e-01
 9.87932319e-01 3.37547053e-01 7.58339398e-01 4.00055015e-01
 8.55158141e-01 8.70242912e-01 8.71777127e-01 8.32407309e-01
 7.19588698e-01 4.98987164e-01 7.42590501e-01 1.89384992e-01
 1.33760724e-01 2.01402674e-01 1.40040130e-01 2.00984639e-01
 4.42959666e-01 8.18071095e-01 7.22419482e-01 9.11070516e-01
 6.86683882e-01 5.07983205e-01]
The mean of the random array is  0.5578549188904803

 Random 10 * 10 matrix 
[[0.68515112 0.62395723 0.40067521 0.93800106 0.63455831 0.93184418
  0.89579198 0.0031865  0.89671682 0.07588422]
 [0.30511931 0.22043292 0.2867102  0.97810362 0.6969246  0.679106
  0.48812795 0.91515323 0.70538125 0.04014133]
 [0.82643269 0.5978361  0.60249671 0.38453735 0.47912122 0.77035305
  0.42269618 0.52496604 0.05475207 0.2515704 ]
 [0.34933296 0.59665668 0.59479619 0.46411346 0.28587353 0.53841835
  0.43446584 0.06432351 0.14498732 0.97454336]
 [0.69

In [39]:
#creating zeroa array and replaing elements
zerosArray=np.zeros(10)
print(zerosArray)
zerosArray[5]=1
print(zerosArray)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [45]:
arr = [1,2,0,0,4,0]
np_arr=np.array(arr)
print("orginal array",np_arr)
reversed_array=np.flip(np_arr)
print("Reversed array",reversed_array)
print(np_arr[0])



orginal array [1 2 0 0 4 0]
Reversed array [0 4 0 0 2 1]
1


In [50]:
boarder_array = np.zeros((7, 7), dtype=int)


boarder_array[0, :] = 1          
boarder_array[-1, :] = 1         
boarder_array[:, 0] = 1     
boarder_array[:, -1] = 1         

print(boarder_array)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [51]:
row_pattern = np.array([0, 1] * 4)

checkerboard = np.tile(row_pattern, (8, 1))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [52]:
import numpy as np


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr4 = np.array([10, 11, 12])

add_result = arr1 + arr2
print("Addition result:", add_result)


subtract_result = arr1 - arr2
print("Subtraction result:", subtract_result)


multiply_result = arr1 * 3
print("Multiplication result (arr1 * 3):", multiply_result)

square_result = np.square(arr1)
print("Square of each element:", square_result)


dot_arr1_arr2 = np.dot(arr1, arr2)
dot_arr3_arr1 = np.dot(arr3, arr1)
dot_arr3_arr4 = np.dot(arr3, arr4)

print("Dot product arr1·arr2:", dot_arr1_arr2)
print("Dot product arr3·arr1:", dot_arr3_arr1)
print("Dot product arr3·arr4:", dot_arr3_arr4)


concat_arr3_arr4 = np.concatenate((arr3, arr4), axis=0)
print("Concatenation of arr3 and arr4 along rows:", concat_arr3_arr4)

concat_arr1_arr2 = np.concatenate((arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=1)
print("Concatenation of arr1 and arr2 along columns:", concat_arr1_arr2)


try:
    concat_arr3_arr1 = np.concatenate((arr3, arr1), axis=1)
    print("Concatenation of arr3 and arr1 along columns:", concat_arr3_arr1)
except ValueError as e:
    print("Error encountered:", e)

concat_arr3_arr1_fixed = np.concatenate((arr3.reshape(-1, 1), arr1.reshape(-1, 1)), axis=1)
print("Concatenation of arr3 and arr1 after reshaping:", concat_arr3_arr1_fixed)


Addition result: [5 7 9]
Subtraction result: [-3 -3 -3]
Multiplication result (arr1 * 3): [3 6 9]
Square of each element: [1 4 9]
Dot product arr1·arr2: 32
Dot product arr3·arr1: 50
Dot product arr3·arr4: 266
Concatenation of arr3 and arr4 along rows: [ 7  8  9 10 11 12]
Concatenation of arr1 and arr2 along columns: [[1 4]
 [2 5]
 [3 6]]
Error encountered: axis 1 is out of bounds for array of dimension 1
Concatenation of arr3 and arr1 after reshaping: [[7 1]
 [8 2]
 [9 3]]


In [53]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
I = np.array([[1, 0], [0, 1]])

result_AA_inv = np.dot(A, A_inv)
print("A * A_inv = \n", result_AA_inv)
print("Identity matrix I = \n", I)

B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)

AB_T = np.transpose(np.dot(A, B))
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T = \n", AB_T)
print("B^T * A^T = \n", B_T_A_T)

A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("Solution (x, y, z) = \n", X)


A * A_inv = 
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
Identity matrix I = 
 [[1 0]
 [0 1]]
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
(AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
Solution (x, y, z) = 
 [ 2.  1. -2.]
